export const rowData = [
  {
    name: 'John Jay Rimorin',
    assignedTo: 'Lloyd Joseph Miguel',
    hiredDate: '08/02/2022',
    state: 'Onboarding',
    jobLevel: 'Developer',
    project: '',
    id: '0001',
  },
  {
    name: 'hans Gustaf Capiral',
    assignedTo: 'Lloyd Joseph Miguel',
    hiredDate: '08/02/2022',
    state: 'Onboarding',
    jobLevel: 'Developer',
    project: '',
    id: '0002',
  },
  {
    name: 'Rosemarie Osinsao',
    assignedTo: 'Lloyd Joseph Miguel',
    hiredDate: '08/02/2022',
    state: 'Onboarding',
    jobLevel: 'Senior Developer',
    project: 'Fleet Response',
    id: '0003',
  },
  {
    name: 'Erwin Data',
    assignedTo: 'Lloyd Joseph Miguel',
    hiredDate: '08/02/2022',
    state: 'Onboarding',
    jobLevel: 'Developer',
    project: '',
    id: '0004',
  },
  {
    name: 'Kirstin Megga Ramos',
    assignedTo: 'Lloyd Joseph Miguel',
    hiredDate: '08/02/2022',
    state: 'Onboarding',
    jobLevel: 'Developer',
    project: '',
    id: '0005',
  },
];
